const BASE_GOOGLE_PLACE_URL = 'https://maps.googleapis.com/maps/api/place/';
const BASE_IMAGE_API = `photo?maxwidth=400&photoreference=`;
const DB_USERS_COLLECTION_NAME = 'BLA_BLA_CAR_USERS';
const DB_TRIPS_COLLECTION_NAME = 'BLA_BLA_CAR_TRIPS';
const BLA_BLA_CAR_LINKER_TRIPS = 'BLA_BLA_CAR_LINKER_TRIPS';

export default {
    BASE_IMAGE_API,
    BASE_GOOGLE_PLACE_URL,
    DB_USERS_COLLECTION_NAME,
    DB_TRIPS_COLLECTION_NAME,
    BLA_BLA_CAR_LINKER_TRIPS,
};
