export const GO_TO_THE_MAIN_MENU = 'Головне меню';
export const NEXT_CITY_IN_THE_TRIP = 'Наступне місто у подорожі';
export const FINAL_CITY_IN_THE_TRIP = 'Це кінцеве місто у подорожі';

export const MONTH_DOWN = 'MONTH_DOWN';
export const MONTH_UP = 'MONTH_UP';
export const DATE_CHANGED = 'DATE_CHANGED';
export const SET_TRIP_HOUR = 'SET_TRIP_HOUR';
export const SET_TRIP_MINUTES = 'SET_TRIP_MINUTES';
export const CHOOSE_TRIP_CITY = 'CHOOSE_TRIP_CITY';
export const CONFIRM_TRIP_DATE = 'підтвердити';
export const START_CITIES_CREATING ='START_CITIES_CREATING';
export const SET_AVAILABLE_SEATS_CUNT = 'SET_AVAILABLE_SEATS_CUNT';
export const GO_TO_TIME_PICKER = 'Далі';
export const GO_TO_TRIP_END_TIME_PICKER = 'Перейти до часу прибуття';
export const GO_TO_AVAILABLE_SEATS_SETTING = 'Вказати вільні місця';
export const AVAILABLE_SEATS_MESSAGE = 'Вкажіть кількість вільних місць';
export const PROPOSE_TRIP ='Запропонувати поїздку';

export const TRIP_END_TIME_PICKER_MESSAGE = 'Уведіть Дату приїзду будь ласка';
export const CHOOSE_ROLE_MESSAGE = 'Виберіть роль';
export const CHOOSE_CITY_MESSAGE = 'Будь ласка виберіть правильне місто';
export const NOT_FOUND_CITY_MESSAGE = 'Нажаль ми не знайшли такого міста :(';
export const START_MESSAGE = '/start';
export const TIME_CHOOSING_MESSAGE = 'Оберіть годину будь ласка!';
export const CALENDAR_START_TRIP_MESSAGE = 'Оберіть дату вашої поїздки будь ласка!';
export const CALENDAR_STOP_TRIP_MESSAGE = 'Оберіть дату вашо вашого прибуття будь ласка!';
export const CALENDAR_CONGRATS_MESSAGE = 'Молодець! а зараз вкажи дату відправлення!';
export const CITIES_INITIAL_HELP_TEXT = 'Напишіть місто виїзду, наприклад Київ';
